// EXEMPLOS
export const USER_INSTALL_IS_LOADING = 'USER_INSTALL_IS_LOADING';
export const USER_INSTALL_ALL_DATA = 'USER_INSTALL_ALL_DATA';

export const USER_INSTALL_BFF_ALL_DATA = 'USER_INSTALL_BFF_ALL_DATA';

export const LOGIN_URL = 'LOGIN_URL';

export const FREE_INTERNET = 'FREE_INTERNET';

export const B2C_DATA = 'B2C_DATA';

export const REGISTRATION_TYPE = 'REGISTRATION_TYPE';

export const BFF_AUTH_IS_LOADING = 'BFF_AUTH_IS_LOADING';
